dist: 
sudo: required
language: node_js
node_js:
  - "10"
before_install: cd /data/www
clone_folder: /data/www # выбираем локальную директорию для клонирования
shallow_clone: true
cache:
  directories:
    - "node_modules"
  npm: true
script:  
    - pwd